blm6191_coverage_planner:
  robot_radius: 0.30      # Robotun metre cinsinden yarıçapı. Tarama genişliğini belirler (2 * yarıçap).
                          # Bu değer, tarama çizgileri arasındaki mesafeyi etkiler.
  polygon_topic: "coverage_polygon" # geometry_msgs/Polygon mesajının yayınlanacağı konu (topic) adı.
