move_base:

  base_global_planner: blm6191_coverage_planner/CoveragePlanner

  blm6191_coverage_planner: 
    robot_radius: 0.30      # Robotun yarıçapı (metre cinsinden)
    polygon_topic: "coverage_polygon" # Kapsama alanı poligonunun yayınlandığı topic adı
